config/routes.rb
Rails.application.routes.draw do
  get 'admins/guest_sign_in', to: 'admins#guest_sign_in'
  get 'users/guest_sign_in',  to: 'users#guest_sign_in'
  get 'users/account',        to: 'users#account'
  get 'celebrities/search',   to: 'celebrities#search'
  get 'cinemas/search',       to: 'cinemas#search'
  resource :users, only: [:destroy]

  scope '/users' do
    resource :profile, only: [:show, :update]
  end

  resources :celebrities, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :genres, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :cinemas, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :reviews, only: [:new, :create, :edit, :update]

  resources :admins, only: [:index]
  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'cinemas#index'
end

app/models/genre.rb
class Genre < ApplicationRecord
  # belongs_to :cinema

  validates :name, presence: true, length: { maximum: 20 }, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      flash[:notice] = "ジャンルを作成しました"
      redirect_to genres_path
    else
      flash[:errors_full_messages] = @genre.errors.full_messages
      render "new"
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル名を更新しました"
      redirect_to genres_path
    else
      flash[:errors_full_messages] = @genre.errors.full_messages
      render "edit"
    end
  end

  def show
  end

  def destroy
    if current_admin.email == GUEST_EMAIL
      flash[:alert] = "ゲストユーザーは削除権限がありません"
      render "edit"
    elsif @genre.destroy
      flash[:notice] = "ジャンル名を削除しました"
      redirect_to genres_path
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/edit.html.erb
<div class="container genre genre-edit">
  <div class="genre-edit-view">
    <div class="genre-edit-view-box">
      <h1>ジャンル編集</h1>
      <div class="genre-inner">
        <%= form_with model: @genre do |f| %>
          <div class="create-content">
            <%= f.label :name, class: "required-a" %><br />
            <%= f.text_field :name, placeholder: "ジャンル名", autocomplete: "name", required: true, class: "form-control input-w", value: @genre.name %>
          </div>
          <div class="create-content">
            <%= f.submit "更新", class: "btn btn-primary" %>
          </div>
        <% end %>

        <div class="actions">
            <%= link_to "削除", genre_path, class: "btn btn-primary", data: { method: :delete, confirm: "本当に削除しますか？" } %>
          </div>
        <div class="actions">
          <%= link_to "戻る", :back, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container genre genre-new">
  <div class="genre-new-view">
    <div class="genre-new-view-box">
      <h1>ジャンル</h1>
      <div class="genre-index">
        <div class="genre-list">
          <table>
            <thead>
              <th>Id</th>
              <th>ジャンル名</th>
            </thead>
            <tbody>
              <% @genres.each do |genre| %>
                <tr>
                  <td><%= genre.id %></td>
                  <td><%= link_to genre.name, edit_genre_path(genre), data: {"turbolinks": false} %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="actions">
          <%= link_to "ジャンル 新規作成", new_genre_path, data: {"turbolinks": false}, class: "use-border" %><br />
        </div>
        <div class="actions">
          <%= link_to "戻る", :back, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/genres/new.html.erb
<div class="container genre genre-new">
  <div class="genre-new-view">
    <div class="genre-new-view-box">
      <h1>ジャンル新規作成</h1>
      <div class="genre-inner">
        <%= form_with model: @genre do |f| %>
          <div class="create-content">
            <%= f.label :name, class: "required-a" %><br />
            <%= f.text_field :name, placeholder: "ジャンル名", autocomplete: "name", required: true, class: "form-control input-w" %>
          </div>
          <div class="create-content">
            <%= f.submit "作成", class: "btn btn-primary" %>
          </div>
        <% end %>

        <div class="actions">
          <%= link_to "戻る", :back, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/genres/show.html.erb
<h1>Genres#show</h1>
<p>Find me in app/views/genres/show.html.erb</p>