config/routes.rb
Rails.application.routes.draw do
  get 'admins/guest_sign_in', to: 'admins#guest_sign_in'
  get 'users/guest_sign_in',  to: 'users#guest_sign_in'
  get 'users/account',        to: 'users#account'
  get 'celebrities/search',   to: 'celebrities#search'
  get 'cinemas/search',       to: 'cinemas#search'
  resource :users, only: [:destroy]

  scope '/users' do
    resource :profile, only: [:show, :update]
  end

  resources :celebrities, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :genres, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :cinemas, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :reviews, only: [:new, :create, :edit, :update]

  resources :admins, only: [:index]
  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'cinemas#index'
end

app/models/celebrity.rb
class Celebrity < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true, length: { maximum: 20 }
  validates :ruby, presence: true, length: { maximum: 20 }
  validates :date_of_birth, presence: true
  validates :birthplace, presence: true, length: { maximum: 20 }
  validates :history, presence: true, length: { maximum: 1000 }
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController
  before_action :set_celebrity, only: [:show, :edit, :update, :destroy]

  def new
    @celebrity = Celebrity.new
  end

  def create
    @celebrity = Celebrity.new(celebrity_params)

    if @celebrity.save
      flash[:notice] = "著名人を作成しました"
      redirect_to admins_path
    else
      flash[:errors_full_messages] = @celebrity.errors.full_messages
      render "new"
    end
  end

  def edit
  end

  def update
    if @celebrity.update(celebrity_params)
      flash[:notice] = "著名人を更新しました"
      redirect_to admins_path
    else
      flash[:errors_full_messages] = @celebrity.errors.full_messages
      render "edit"
    end
  end

  def show
  end

  def destroy
    if current_admin.email == GUEST_EMAIL
      flash[:alert] = "ゲストユーザーは削除権限がありません"
      render "edit"
    elsif @celebrity.destroy
      flash[:notice] = "著名人を削除しました"
      redirect_to admins_path
    else
      render "edit"
    end
  end

  def search
    @celebrities = Celebrity.where("name LIKE ?", "#{params[:name]}%").limit(10)
  end

  private

  def set_celebrity
    @celebrity = Celebrity.find(params[:id])
  end

  def celebrity_params
    params.require(:celebrity).permit(:name, :ruby, :date_of_birth, :birthplace, :history, :image)
  end
end

app/helpers/celebrities_helper.rb
module CelebritiesHelper
end

app/views/celebrities/edit.html.erb
<div class="container celebrity celebrity-edit">
  <div class="celebrity-new-view">
    <div class="celebrity-new-view-box">
      <h1>著名人編集</h1>
      <div class="celebrity-inner">
        <%= form_with model: @celebrity do |f| %>
          <div class="create-content">
            <div class="row">
              <div class="offset">
              <div class="icon-box">
                <% if @celebrity.image.present? %>
                  <%= image_tag @celebrity.image, alt: "著名人画像", class: "icon-image host-icon" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="create-content">
            <%= f.label :image, class: "required-a" %><br />
            <%= f.file_field :image, required: false, class: "input-w" %>
          </div>
          <div class="create-content">
            <%= f.label :ruby, class: "required-a" %><br />
            <%= f.text_field :ruby, placeholder: "なまえ", autocomplete: "ruby", required: true, class: "form-control input-w", value: @celebrity.ruby %>
          </div>
          <div class="create-content">
            <%= f.label :name, class: "required-a" %><br />
            <%= f.text_field :name, placeholder: "名前", autocomplete: "name", required: true, class: "form-control input-w", value: @celebrity.name %>
          </div>
          <div class="create-content">
            <%= f.label :date_of_birth, class: "required-a" %><br />
            <%= f.date_field :date_of_birth, autofocus: true, autocomplete: "date_of_birth", required: true, class: "form-control", value: @celebrity.date_of_birth %>
          </div>
          <div class="create-content">
            <%= f.label :birthplace, class: "required-a" %><br />
            <%= f.text_field :birthplace, placeholder: "出身地", required: true, class: "form-control input-w", value: @celebrity.birthplace %>
          </div>
          <div class="create-content">
            <%= f.label :history, class: "required-a" %><br />
            <%= f.text_area :history, placeholder: "歴史", required: true, class: "form-control input-w", value: @celebrity.history %>
          </div>
          <div class="create-content">
            <%= f.submit "更新", class: "btn btn-primary" %>
          </div>
        <% end %>

        <div class="actions">
            <%= link_to "削除", celebrity_path, class: "btn btn-primary", data: { method: :delete, confirm: "本当に削除しますか？" } %>
          </div>
        <div class="actions">
          <%= link_to "戻る", :back, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/celebrities/new.html.erb
<div class="container celebrity celebrity-new">
  <div class="celebrity-new-view">
    <div class="celebrity-new-view-box">
      <h1>著名人新規作成</h1>
      <div class="celebrity-inner">
        <%= form_with model: @celebrity do |f| %>
          <div class="create-content">
            <div class="offset">
              <div class="icon-box">
                <% if @celebrity.image.present? %>
                  <%= image_tag @celebrity.image, alt: "著名人画像", class: "celebrity-image" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="create-content">
            <%= f.label :image, class: "required-a" %><br />
            <%= f.file_field :image, required: false, required: true, class: "input-w" %>
          </div>
          <div class="create-content">
            <%= f.label :ruby, class: "required-a" %><br />
            <%= f.text_field :ruby, placeholder: "なまえ", autocomplete: "ruby", required: true, class: "form-control input-w" %>
          </div>
          <div class="create-content">
            <%= f.label :name, class: "required-a" %><br />
            <%= f.text_field :name, placeholder: "名前", autocomplete: "name", required: true, class: "form-control input-w" %>
          </div>
          <div class="create-content">
            <%= f.label :date_of_birth, class: "required-a" %><br />
            <%= f.date_field :date_of_birth, autofocus: true, autocomplete: "date_of_birth", required: true, class: "form-control", value: @celebrity.date_of_birth %>
          </div>
          <div class="create-content">
            <%= f.label :birthplace, class: "required-a" %><br />
            <%= f.text_field :birthplace, placeholder: "出身地", required: true, class: "form-control input-w" %>
          </div>
          <div class="create-content">
            <%= f.label :history, class: "required-a" %><br />
            <%= f.text_area :history, placeholder: "歴史", required: true, class: "form-control input-w" %>
          </div>
          <div class="create-content">
            <%= f.submit "作成", class: "btn btn-primary" %>
          </div>
        <% end %>

        <div class="actions">
          <%= link_to "戻る", :back, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/celebrities/search.html.erb
<div class="celebrity-search">
  <% @celebrities.each do |celebrity| %>
    <% if admin_signed_in? %>
      <%= link_to edit_celebrity_path(celebrity), data: {"turbolinks": false} do %>
        <%= image_tag celebrity.image, alt: "著名人画像", class: "celebrity-image" %>
        <p><%= celebrity.name %></p>
      <% end %>
    <% else %>
      <%= link_to celebrity_path(celebrity), data: {"turbolinks": false} do %>
        <%= image_tag celebrity.image, alt: "著名人画像", class: "celebrity-image" %>
        <p><%= celebrity.name %></p>
      <% end %>
    <% end %>
  <% end %>
  <div class="actions">
    <% if admin_signed_in? %>
      <%= link_to "戻る", admins_path, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
    <% else %>
      <%= link_to "戻る", root_path, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
    <% end %>
  </div>
</div>

app/views/celebrities/show.html.erb
<div class="container celebrity celebrity-show">
  <div class="celebrity-show-view">
    <div class="celebrity-inner">
      <div class="offset">
        <div class="icon-box">
          <%= image_tag @celebrity.image, alt: "著名人画像", class: "celebrity-image" %>
        </div>
      </div>
      <div class="create-content">
        <%= label :celebrity, :ruby %><br />
        <p class="celebrity-ruby"><%= @celebrity.ruby %></p>
      </div>
      <div class="create-content">
        <%= label :celebrity, :name %><br />
        <p class="celebrity-name"><%= @celebrity.name %></p>
      </div>
      <div class="create-content">
        <%= label :celebrity, :date_of_birth %><br />
        <p class="celebrity-date-of-birth"><%= @celebrity.date_of_birth %></p>
      </div>
      <div class="create-content">
        <%= label :celebrity, :birthplace %><br />
        <p class="celebrity-birthplace"><%= @celebrity.birthplace %></p>
      </div>
      <div class="create-content">
        <%= label :celebrity, :history %><br />
        <p class="celebrity-history"><%= @celebrity.history %></p>
      </div>

      <div class="actions">
        <%= link_to "戻る", root_path, class: "btn btn-outline-secondary form-control", data: {"turbolinks": false} %>
      </div>
    </div>
  </div>
</div>