config/routes.rb
Rails.application.routes.draw do
  get 'admins/guest_sign_in', to: 'admins#guest_sign_in'
  get 'users/guest_sign_in',  to: 'users#guest_sign_in'
  get 'users/account',        to: 'users#account'
  get 'celebrities/search',   to: 'celebrities#search'
  get 'cinemas/search',       to: 'cinemas#search'
  resource :users, only: [:destroy]

  scope '/users' do
    resource :profile, only: [:show, :update]
  end

  resources :celebrities, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :genres, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :cinemas, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :reviews, only: [:new, :create, :edit, :update]

  resources :admins, only: [:index]
  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions' }
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'cinemas#index'
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <p class="flash flash_notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:notice_green] %>
  <p class="flash_notice_green"><%= flash[:notice_green] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="alert flash_alert"><%= flash[:alert] %></p>
<% end %>
<% if flash[:errors_full_messages] and (admin_signed_in? or user_signed_in?) %>
  <ul class="flash flash_errors">
    <% flash[:errors_full_messages].each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>©︎ 2022 S.K</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-left-nav">
    <%= render "shared/search" %>
  </div>
  <div class="header-right-nav">
    <% if admin_signed_in? %>
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, data: {"turbolinks": false} %>
    <% elsif user_signed_in? %>
      <div class="nav-item"><%= image_tag current_user.profile.image, alt: "アイコン画像", class: "host-icon" %></div>
      <div class="nav-item">
        <%= link_to "設定", users_account_path, data: {"turbolinks": false} %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {"turbolinks": false} %>
      </div>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, data: {"turbolinks": false} %>
      <%= link_to "登録する", new_user_registration_path, data: {"turbolinks": false} %>
    <% end %>
  </div>
</header>

app/views/shared/_search.html.erb
<%= form_with url: cinemas_search_path, method: :get do |f| %>
  <div class="header-search">
    <%= f.text_field :title, placeholder: "映画タイトル", class: "form-control" %>
  </div>
<% end %>
<%= form_with url: celebrities_search_path, method: :get do |f| %>
  <div class="header-search">
  <%= f.text_field :name, placeholder: "著名人", class: "form-control" %>
  </div>
<% end %>